---

# Debian family installation tasks

- name: 'INSTALL | APT | Add GPG key'
  apt_key:
    id: "{{ alignak_repository_key }}"
    keyserver: "{{ alignak_repository_keyserver }}"
    state: 'present'
  when: "{{ alignak_repository_key != '' }}"


- name: 'INSTALL | APT | Configure repository'
  template:
    src: 'templates/apt_repository.list.j2'
    dest: "/etc/apt/sources.list.d/{{ alignak_repository_file_name }}"
    owner: 'root'
    group: 'root'
    mode: "{{ alignak_repository_file_mode }}"
  register: 'alignak_check_repository_file'


- name: 'INSTALL | APT | Update cache if repository file updated'
  apt:
    update_cache: True
  when: "{{ alignak_check_repository_file | changed }}"


- name: 'INSTALL | APT | Install packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    update_cache: "{{ alignak_apt_update_cache }}"
    cache_valid_time: "{{ alignak_apt_cache_valid_time }}"
  with_items: "{{ alignak_packages }}"
